# Generated by Django 4.2.14 on 2024-08-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
